module.exports = {
    'array-bracket-newline': ['error'],
    'block-spacing': ['error'],
    'brace-style': ['error'],
    'camelcase': ['error'],
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': ['error'],
    'comma-style': ['error'],
    'computed-property-spacing': ['error', 'never'],
    'consistent-this': ['error'],
    'eol-last': ['error'],
    'func-call-spacing': ['error'],
    'indent': ['error', 4, {
        'SwitchCase': 1,
    }],
    'key-spacing': ['error'],
    'keyword-spacing': ['error'],
    'linebreak-style': ['error'],
    'lines-around-comment': ['error', {
        'beforeBlockComment': true,
    }],
    'lines-between-class-members': ['error', 'always'],
    'max-depth': ['warn', 4],
    'max-nested-callbacks': ['error', 5],
    'max-params': ['warn', 5],
    'max-statements-per-line': ['error'],
    'new-parens': ['error'],
    'no-array-constructor': ['error'],
    'no-bitwise': 'warn',
    'no-lonely-if': ['error'],
    'no-mixed-spaces-and-tabs': ['error'],
    'no-multi-assign': ['error'],
    'no-nested-ternary': ['error'],
    'no-new-object': ['error'],
    'no-tabs': ['error'],
    'no-trailing-spaces': ['error'],
    'no-unneeded-ternary': ['error'],
    'no-whitespace-before-property': ['error'],
    'require-jsdoc': 'warn',
    'semi': ['error'],
    'semi-style': ['error', 'last'],
    'space-before-blocks': ['error'],
    'space-before-function-paren': 'off',
    'space-infix-ops': ['error'],
    'switch-colon-spacing': ['error'],
    'template-tag-spacing': ['error'],
};
