const chartActions = {
    CHANGE_CHART: 'CHANGE_CHART',

    CREATE_CHART_START: 'CREATE_CHART_START',
    CREATE_CHART_SUCCESS: 'CREATE_CHART_SUCCESS',
    CREATE_CHART_ERROR: 'CREATE_CHART_ERROR',

    UPDATE_CHART_START: 'UPDATE_CHART_START',
    UPDATE_CHART_SUCCESS: 'UPDATE_CHART_SUCCESS',
    UPDATE_CHART_ERROR: 'UPDATE_CHART_ERROR',

    DELETE_CHART_START: 'DELETE_CHART_START',
    DELETE_CHART_SUCCESS: 'DELETE_CHART_SUCCESS',
    DELETE_CHART_ERROR: 'DELETE_CHART_ERROR',
};

const groupActions = {
    CREATE_GROUP_START: 'CREATE_GROUP_START',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    CREATE_GROUP_ERROR: 'CREATE_GROUP_ERROR',

    UPDATE_GROUP_START: 'UPDATE_GROUP_START',
    UPDATE_GROUP_SUCCESS: 'UPDATE_GROUP_SUCCESS',
    UPDATE_GROUP_ERROR: 'UPDATE_GROUP_ERROR',

    DELETE_GROUP_START: 'DELETE_GROUP_START',
    DELETE_GROUP_SUCCESS: 'DELETE_GROUP_SUCCESS',
    DELETE_GROUP_ERROR: 'DELETE_GROUP_ERROR',
};

const reminderActions = {
    CREATE_REMINDER_START: 'CREATE_REMINDER_START',
    CREATE_REMINDER_SUCCESS: 'CREATE_REMINDER_SUCCESS',
    CREATE_REMINDER_ERROR: 'CREATE_REMINDER_ERROR',

    UPDATE_REMINDER_START: 'UPDATE_REMINDER_START',
    UPDATE_REMINDER_SUCCESS: 'UPDATE_REMINDER_SUCCESS',
    UPDATE_REMINDER_ERROR: 'UPDATE_REMINDER_ERROR',

    DELETE_REMINDER_START: 'DELETE_REMINDER_START',
    DELETE_REMINDER_SUCCESS: 'DELETE_REMINDER_SUCCESS',
    DELETE_REMINDER_ERROR: 'DELETE_REMINDER_ERROR',
};

const loginActions = {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
};

const usageActions = {
    USAGE_START: 'USAGE_START',
    USAGE_SUCCESS: 'USAGE_SUCCESS',
    USAGE_ERROR: 'USAGE_ERROR',
};

const usageStreamActions = {
    USAGE_STREAM_START: 'USAGE_STREAM_START',
    USAGE_STREAM_SUCCESS: 'USAGE_STREAM_SUCCESS',
    USAGE_STREAM_ERROR: 'USAGE_STREAM_ERROR',
};

const queryActions = {
    FETCH_ENTITY_START: 'FETCH_ENTITY_START',
    FETCH_ENTITY_SUCCESS: 'FETCH_ENTITY_SUCCESS',
    FETCH_ENTITY_ERROR: 'FETCH_ENTITY_ERROR',
    EXTRACT_CHANNELS: 'EXTRACT_CHANNELS',
};

const queryAllActions = {
    FETCH_ALL: 'FETCH_ALL',
    FETCH_ALL_NEW: 'FETCH_ALL_NEW',
    FETCH_ALL_START: 'FETCH_ALL_START',
    FETCH_ALL_SUCCESS: 'FETCH_ALL_SUCCESS',
    FETCH_ALL_ERROR: 'FETCH_ALL_ERROR',
    FETCH_ALL_FINISH: 'FETCH_ALL_FINISH',
    EXTRACT_ALL_CHANNELS: 'EXTRACT_ALL_CHANNELS',
};


const streamActions = {
    STREAM_CONNECT: 'STREAM_CONNECT',
    STREAM_CONNECT_ERROR: 'STREAM_CONNECT_ERROR',
    STREAM_RECONNECTING: 'STREAM_RECONNECTING',
    STREAM_DISCONNECT: 'STREAM_DISCONNECT',
    STREAM_CLOSE: 'STREAM_CLOSE',

    STREAM_PAUSE: 'STREAM_PAUSE',

    STREAM_NEW: 'STREAM_NEW',
    STREAM_RESULT: 'STREAM_RESULT',
    STREAM_ERROR: 'STREAM_ERROR',
};

export default {
    ...chartActions,
    ...groupActions,
    ...loginActions,
    ...queryActions,
    ...queryAllActions,
    ...usageActions,
    ...usageStreamActions,
    ...reminderActions,
    ...streamActions,

    CHANGE_USER: 'CHANGE_USER',
    SET_USER_ID: 'SET_USER_ID',

    CHANGE_CHART_TAB: 'CHANGE_CHART_TAB',
    SET_SIDEBAR_VISIBILITY: 'SET_SIDEBAR_VISIBILITY',

    SET_MODAL_VISIBILITY: 'SET_MODAL_VISIBILITY',
    TOGGLE_LOGIN_MODAL: 'TOGGLE_LOGIN_MODAL',
    TOGGLE_NEW_USER_MODAL: 'TOGGLE_NEW_USER_MODAL',

    SELECT_SEARCH: 'SELECT_SEARCH',
    CHANGE_SETTINGS_TAB: 'CHANGE_SETTINGS_TAB',
    CHANGE_ACTIVE_GROUP: 'CHANGE_ACTIVE_GROUP',
    CHANGE_ACTIVE_DEVICE: 'CHANGE_ACTIVE_DEVICE',
    CHANGE_ACTIVE_CHANNEL: 'CHANGE_ACTIVE_CHANNEL',

    TOOGLE_EDIT_MODAL: 'TOOGLE_EDIT_MODAL',
    CHANGE_EDIT_TAB: 'CHANGE_EDIT_TAB',
};
