export default {
    CHANGE_USER: 'CHANGE_USER',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    SET_MODAL_VISIBILITY: 'SET_MODAL_VISIBILITY',
};
